  services:
    web:
      build:
        context: .
        dockerfile: Dockerfile-web
      container_name: web
      ports:
        - "8800:80"
      volumes:
        - ./src:/var/www/html
      depends_on:
        - db
    db:
      build:
        context: .
        dockerfile: Dockerfile-db
      container_name: db
      environment:
        MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
        MYSQL_DATABASE: ${DATABASE}
        MYSQL_USER: ${USER}
        MYSQL_PASSWORD: ${USER_PASSWORD}
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql
        - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  volumes:
    mysql_data:
      # Define volume for persisting MySQL data
