  services:
    web:
      build:
        context: .
        dockerfile: Dockerfile-web
      container_name: web
      ports:
        - "8800:80"
      volumes:
        - ./src:/var/www/html
      depends_on:
        - db
      env_file:
        - .env
    db:
      build:
        context: .
        dockerfile: Dockerfile-db
      container_name: db
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql

  volumes:
    mysql_data: {}
      # Define volume for persisting MySQL data
